name: Build Open Br Official

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    # Ganti bagian Setup Gradle Wrapper dengan ini
    - name: Setup Gradle Wrapper
      run: |
        # Kita pakai perintah curl saja biar pasti dapet versi 8.2, jangan pakai perintah 'gradle' bawaan runner
        curl -LO https://services.gradle.org/distributions/gradle-8.2-bin.zip
        unzip -q gradle-8.2-bin.zip
        ./gradle-8.2/bin/gradle wrapper --gradle-version 8.2
        chmod +x gradlew

    - name: Build Release APK
      run: ./gradlew assembleRelease
    - name: Sign APK
      uses: r0adkll/sign-android-release@v1
      id: sign_app
      with:
        releaseDirectory: app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
        # TAMBAHKAN BARIS INI BIAR GAK NYARI VERSI LAMA
        buildToolsVersion: "34.0.0" 

    # Upload hasil akhir yang sudah resmi
    - name: Upload Official APK
      uses: actions/upload-artifact@v4
      with:
        name: OpenBr_v17.17
        path: ${{ steps.sign_app.outputs.signedReleaseFile }}
        
